package edu.nextstep.game;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class BaseballGamerTest {
	@Test
	@DisplayName("generateComputer : 자동 생성된 selectedNumber를 가지는 BaseballGamer가 리턴되어야 함")
	void generateComputer_ShouldReturnBaseballGamerWithAutoGeneratedSelectedNumber() {
		// given

		// when
		int numberSize = 3;
		BaseballGamer gamer = BaseballGamer.generateComputer(numberSize);

		// then
		assertNotNull(gamer.getSelectedNumber());
		assertEquals(gamer.getSelectedNumber().length(), numberSize);
	}
}