package edu.nextstep.game;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class BaseballGamerTest {
	@Test
	@DisplayName("generateComputer : 자동 생성된 selectedNumber를 가지는 BaseballGamer가 리턴되어야 함")
	void generateComputer_ShouldReturnBaseballGamerWithAutoGeneratedSelectedNumber() {
		// given

		// when
		int numberSize = 3;
		BaseballGamer gamer = BaseballGamer.generateComputer(numberSize);

		// then
		assertNotNull(gamer.getSelectedNumber());
		assertEquals(gamer.getSelectedNumber().length(), numberSize);
	}

	@Test
	@DisplayName("pickDigit : BaseballGamer의 selectedNumber에서 주어진 index에 위치하는 숫자 하나가 리턴되어야 함")
	void pickDigit_ShouldReturnOneDigitAtTheGivenIndexInSelectedNumber() {
		// given
		int numberSize = 3;
		BaseballGamer gamer = BaseballGamer.generateComputer(numberSize);
		String selectedNumber = gamer.getSelectedNumber();

		// when
		int index = 1; // Zero-based
		String digit = gamer.pickDigit(index);

		// then
		assertNotNull(digit);
		assertAll(
			() -> assertEquals(digit.length(), 1),
			() -> assertEquals(digit, String.valueOf(selectedNumber.charAt(index)))
		);
	}
}